# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'tutorialProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tutorialProject
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  target 'tutorialProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tutorialProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tutorialProject-tvOS

  target 'tutorialProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
